### ISSUE TITLE
예약내역 페이지 구현

### ISSUE THREAD

**Issue by lilviolie** [YBEMiniProjectTeam/MINI-Front#30]
## 목적
예약내역 페이지 구현

## 세부 내용
- 예약내역 페이지 마크업
- API 연동

**Comment by im-na0** [comment]
은지님 예약내역 페이지 구현하고 계신가용? 할 일이 더 늘어나신 것 같은데,,😓 이건 이어서 제가 마크업해도 될까용?

**Comment by lilviolie** [comment]
앗 마크업이 할 게 많지 않아서 제가 했습니다..!

**Comment by im-na0** [comment]
> 앗 마크업이 할 게 많지 않아서 제가 했습니다..!

아항 그럼 작업하신거 pr 올려주시면 이어서 로직구현 하겠습니당!!

**Comment by lilviolie** [comment]
이제야 봤네요 죄송해요..! 나영님 혹시 할 게 하나도 없으신게 아니면 요 페이지도 제가 담당해서 해도 될까요?

**Comment by im-na0** [comment]
> 이제야 봤네요 죄송해요..! 나영님 혹시 할 게 하나도 없으신게 아니면 요 페이지도 제가 담당해서 해도 될까요? 컴포넌트가 약간.. 꼬여서용..

아하 혹시 어떻게 꼬이신건가용?? 마크업이 이제 다 끝나서 슬슬 이어붙이려던 참이여서용!!

**Comment by lilviolie** [comment]
나영님 일단 pr 올렸습니다!
